package.path = '/Users/chenjingqiao/.config/nvim/plugin/packer_compiled.lua'
require('basic')
require('plugins')
require('packer_compiled')
require('keybindings')
require("colorscheme")
require('nvim-web-devicons')
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.nvim-treesitter")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("plugin-config.indent-blankline")
require("plugin-config.project")
require("plugin-config.dashboard")
